export { default as HomeView } from './HomeView'
export { default as CartView } from './CartView'
export { default as AuthView } from './AuthView'
export { default as CheckoutView } from './CheckoutView'
export { default as ProductView } from './ProductView'
export { default as Custom404View } from './Custom404View'
